name: CI Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install unittest

      - name: Run tests
        run: |
          python -m unittest discover
